name = "Unitless"
uuid = "c904d999-9673-4878-a3dd-e3ef1851788a"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "2.1.0"

[deps]
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
UnitlessUnitfulExt = "Unitful"

[compat]
Requires = "1"
Unitful = "≥ 1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "Unitful"]
