name = "Unitless"
uuid = "c904d999-9673-4878-a3dd-e3ef1851788a"
authors = ["Éric Thiébaut <eric.thiebaut@univ-lyon1.fr> and contributors"]
version = "2.1.1"

[deps]
TypeUtils = "c3b1956e-8857-4d84-9b79-890df85b1e67"

[compat]
TypeUtils = "1"
Unitful = "≥ 1"
julia = "0.7, 1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "Unitful"]
